logging:
  level: INFO
  loggers:
    minerleague: DEBUG
#mongo:
  #seeds:
  #- host: 69.166.49.230
    #port: 27017
  #database: admin
  #credentials:
    #userName: MLAdmin
    #password: minerleague1
